services:
  postgresql:
    image: bitnami/postgresql:17.0.0
    container_name: postgresql_database
    networks:
      - core-network
    volumes:
      - core-data:/var/lib/postgres/core-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRESQL_PASSWORD: "phamnam123"
      POSTGRESQL_USER: "postgres"
      POSTGRESQL_DATABASE: "core"
      POSTGRESQL_REPLICATION_USE_PASSFILE: false
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  core-network:
volumes:
  core-data:
