// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	CreatePath(ctx context.Context, arg CreatePathParams) (Path, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error)
	ListPaths(ctx context.Context, arg ListPathsParams) ([]Path, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
