// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  role_name, description
) VALUES ($1, $2)
RETURNING id, role_name, description
`

type CreateRoleParams struct {
	RoleName    string      `json:"role_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.RoleName, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName, &i.Description)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, role_name, description FROM roles
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET role_name = coalesce($1, role_name),
    description = coalesce($2, description)
WHERE id = $3
RETURNING id, role_name, description
`

type UpdateRoleParams struct {
	RoleName    pgtype.Text `json:"role_name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.Int8 `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.RoleName, arg.Description, arg.ID)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName, &i.Description)
	return i, err
}
