basePath: /api/v1
consumes:
- application/json
definitions:
  api.RegisterUserRequestParams:
    description: RegisterUserRequestParams để tạo mới 1 tài khoản
    properties:
      email:
        description: Email
        example: namphamhai7@gmail.com
        minLength: 12
        type: string
      full_name:
        description: Họ và tên
        example: Pham Hai Nam
        minLength: 6
        type: string
      password:
        description: Mật khẩu
        example: Password@
        minLength: 6
        type: string
      username:
        description: Tên đăng nhập
        example: phamnam2003
        minLength: 6
        type: string
    required:
    - email
    - full_name
    - password
    - username
    type: object
  database.User:
    properties:
      code_reset_password:
        $ref: '#/definitions/pgtype.Text'
      code_verify_email:
        $ref: '#/definitions/pgtype.Text'
      created_at:
        $ref: '#/definitions/pgtype.Timestamp'
      email:
        type: string
      full_name:
        type: string
      hashed_password:
        type: string
      is_verified_email:
        type: boolean
      password_changed_at:
        $ref: '#/definitions/pgtype.Timestamp'
      role_id:
        type: integer
      token:
        $ref: '#/definitions/pgtype.Text'
      username:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Text:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
  pgtype.Timestamp:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        description: Time zone will be ignored when encoding to PostgreSQL.
        type: string
      valid:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: namphamhai7@gmail.com
    name: API Support
  description: Serve study
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: '[Go Core API]: Core API written by Go'
  version: "1.0"
paths:
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Đăng ký tài khoản (gửi mail để xác nhận tài khoản)
      parameters:
      - description: body
        in: body
        name: identifier
        required: true
        schema:
          $ref: '#/definitions/api.RegisterUserRequestParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.User'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Đăng ký tài khoản
      tags:
      - Authentication
swagger: "2.0"
